<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "titelei"
 *
 * Auto generated by Extension Builder 2015-09-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'titelei',
	'description' => 'titelei is a tool for publishing content into epub on the fly. It integrates Grandt\'s award winning epub library to typo3 ',
	'category' => 'fe',
	'author' => 'Michael Schneider',
	'author_email' => 'Michael Schneider',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.14-7.4.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);